In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.preprocessing import PolynomialFeatures

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
traindf= pd.read_csv("/content/drive/MyDrive/Datasets AIML/11-10-2024/train.csv")
testdf= pd.read_csv("/content/drive/MyDrive/Datasets AIML/11-10-2024/test.csv")

In [ ]:
traindf.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
traindf.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [ ]:
print(traindf.shape)
print(traindf.columns)

(891, 12)
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

**Preprocessing**

In [ ]:
traindf.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
traindf.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
traindf['Age'] = traindf['Age'].fillna(traindf['Age'].mean())

In [ ]:
traindf.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
traindf.drop("PassengerId",axis=1, inplace=True)

In [ ]:
traindf.drop("Name",axis=1, inplace=True)

In [ ]:
len(traindf.columns)

10

In [ ]:
traindf.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age           0
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [ ]:
traindf.dropna(axis=0, how='any', subset="Embarked", inplace=True)
traindf.drop(axis=1,columns='Cabin',inplace=True)

In [ ]:
traindf.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Ticket      0
Fare        0
Embarked    0
dtype: int64

In [ ]:
y_train=traindf['Survived']

In [ ]:
feature=['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Cabin', 'Embarked']

In [ ]:
testdf=testdf[feature]

In [ ]:
testdf['Age'] = testdf['Age'].fillna(testdf['Age'].mean())

<ipython-input-235-2ebebcc1b0ca>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  testdf['Age'] = testdf['Age'].fillna(testdf['Age'].mean())

In [ ]:
testdf.isnull().sum()

Pclass        0
Sex           0
Age           0
SibSp         0
Parch         0
Fare          1
Cabin       327
Embarked      0
dtype: int64

In [ ]:
testdf.drop(axis=1,columns='Cabin',inplace=True)

<ipython-input-237-81487b860e8d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  testdf.drop(axis=1,columns='Cabin',inplace=True)

**Convert Categorical variable to Dummy/Indicator variables**

In [ ]:
traindf=pd.get_dummies(traindf,columns=['Sex'])
testdf=pd.get_dummies(testdf,columns=['Sex'])

In [ ]:
traindf=pd.get_dummies(traindf,columns=['Embarked'])
testdf=pd.get_dummies(testdf,columns=['Embarked'])

In [ ]:
traindf.head()

,Survived,Pclass,Age,SibSp,Parch,Ticket,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,0,3,22.0,1,0,A/5 21171,7.2500,False,True,False,False,True
1,1,1,38.0,1,0,PC 17599,71.2833,True,False,True,False,False
2,1,3,26.0,0,0,STON/O2. 3101282,7.9250,True,False,False,False,True
3,1,1,35.0,1,0,113803,53.1000,True,False,False,False,True
4,0,3,35.0,0,0,373450,8.0500,False,True,False,False,True

In [ ]:
testdf.head()

,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,3,34.5,0,0,7.8292,False,True,False,True,False
1,3,47.0,1,0,7.0000,True,False,False,False,True
2,2,62.0,0,0,9.6875,False,True,False,True,False
3,3,27.0,0,0,8.6625,False,True,False,False,True
4,3,22.0,1,1,12.2875,True,False,False,False,True

In [ ]:
traindf.drop("Survived",axis=1, inplace=True)

**StandardScaler removes the mean and scales each feature/variable to unit variance. This operation performs feature wise in an independent way**

In [ ]:
scaler= StandardScaler()
traindf['Age']=scaler.fit_transform(traindf[['Age']])

In [ ]:
traindf[['Fare']]= scaler.fit_transform(traindf[['Fare']])
testdf[['Age', 'Fare']]= scaler.fit_transform(testdf[['Age', 'Fare']])

In [ ]:
traindf.head()

,Pclass,Age,SibSp,Parch,Ticket,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,3,-0.590495,1,0,A/5 21171,-0.500240,False,True,False,False,True
1,1,0.643971,1,0,PC 17599,0.788947,True,False,True,False,False
2,3,-0.281878,0,0,STON/O2. 3101282,-0.486650,True,False,False,False,True
3,1,0.412509,1,0,113803,0.422861,True,False,False,False,True
4,3,0.412509,0,0,373450,-0.484133,False,True,False,False,True

In [ ]:
testdf.head()

,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,3,0.334993,0,0,-0.497811,False,True,False,True,False
1,3,1.325530,1,0,-0.512660,True,False,False,False,True
2,2,2.514175,0,0,-0.464532,False,True,False,True,False
3,3,-0.259330,0,0,-0.482888,False,True,False,False,True
4,3,-0.655545,1,1,-0.417971,True,False,False,False,True

In [ ]:
testdf['Fare']=testdf['Fare'].fillna(testdf['Fare'].mean())

In [ ]:
testdf.isnull().sum()

Pclass        0
Age           0
SibSp         0
Parch         0
Fare          0
Sex_female    0
Sex_male      0
Embarked_C    0
Embarked_Q    0
Embarked_S    0
dtype: int64

In [ ]:
traindf.isnull().sum()

Pclass        0
Age           0
SibSp         0
Parch         0
Ticket        0
Fare          0
Sex_female    0
Sex_male      0
Embarked_C    0
Embarked_Q    0
Embarked_S    0
dtype: int64

In [ ]:
traindf.drop("Ticket",axis=1, inplace=True)

In [ ]:
train_x,val_x,train_y,val_y= train_test_split(traindf,y_train,train_size=0.8,random_state=52)

In [ ]:
train_x

,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
739,3,0.003524,0,0,-0.487238,False,True,False,False,True
120,2,-0.667649,2,0,0.833576,False,True,False,False,True
641,1,-0.436187,0,0,0.749017,True,False,True,False,False
160,3,1.106896,0,1,-0.322062,False,True,False,False,True
56,2,-0.667649,0,0,-0.434807,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...
87,3,0.003524,0,0,-0.484133,False,True,False,False,True
152,3,1.994168,0,0,-0.484133,False,True,False,False,True
526,2,1.569820,0,0,-0.434807,True,False,False,False,True
780,3,-1.284882,0,0,-0.500659,True,False,True,False,False
669,1,0.003524,1,0,0.400715,True,False,False,False,True

In [ ]:
train_y

739    0
120    0
641    1
160    0
56     1
      ..
87     0
152    0
526    1
780    1
669    1
Name: Survived, Length: 711, dtype: int64

In [ ]:
val_x

,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
560,3,0.003524,0,0,-0.490173,False,True,False,True,False
156,3,-1.053420,0,0,-0.490509,True,False,False,True,False
200,3,-0.127570,0,0,-0.454940,False,True,False,False,True
378,3,-0.744803,0,0,-0.565421,False,True,True,False,False
263,1,0.798279,0,0,-0.646204,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...
182,3,-1.593499,4,2,-0.014278,False,True,False,False,True
414,3,1.106896,0,0,-0.486650,False,True,False,False,True
710,1,-0.436187,0,0,0.350467,True,False,True,False,False
578,3,0.003524,1,0,-0.355115,True,False,True,False,False
246,3,-0.359033,0,0,-0.489670,True,False,False,False,True

In [ ]:
val_y

560    0
156    1
200    0
378    0
263    0
      ..
182    0
414    1
710    1
578    0
246    0
Name: Survived, Length: 178, dtype: int64

Apply Logistic Regression

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(train_x,train_y)

LogisticRegression()

In [ ]:
model.predict(val_x)

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 1])

In [ ]:
accuracy_score(val_y,model.predict(val_x))

0.7528089887640449

In [ ]:
# precision, f1, confusion

precision_score(val_y,model.predict(val_x))

0.6419753086419753

In [ ]:
f1_score(val_y,model.predict(val_x))

0.7027027027027027

In [ ]:
recall_score(val_y,model.predict(val_x))

0.7761194029850746